apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2023-05-11T06:32:21Z"
  generation: 1
  labels:
    app: varun
  name: varun
  namespace: default
  resourceVersion: "218409601"
  uid: e20af8f5-bb22-4ebd-b312-466795285774
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: varun
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: varun
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
